import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: 'Roboto',
    fontSize: 6,
    paddingTop: 30,
    paddingLeft: 60,
    paddingRight: 60,
    paddingBottom: 30,
    backgroundColor: '#ffffff',
  },
  header: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 30,
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#667eea',
    paddingBottom: 15,
    borderBottomWidth: 3,
    borderBottomColor: '#667eea',
  },
  customerInfo: {
    marginBottom: 25,
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e3e8ed',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
  },
  customerTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e3e8ed',
  },
  customerText: {
    fontSize: 12,
    color: '#495057',
    marginBottom: 5,
  },
  partItem: {
    marginBottom: 15,
    padding: 15,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#2c3e50',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
    minHeight: 200,
  },
  partImage: {
    width: '50%',
    height: 180,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e3e8ed',
    backgroundColor: '#f8f9fa',
    objectFit: 'contain',
    flexShrink: 0,
    objectPosition: 'center',
  },
  partContent: {
    width: '50%',
    flex: 1,
    flexShrink: 0,
  },
  partHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    gap: 5,
  },
  partTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2c3e50',
    width: '100%',
    flexWrap: 'wrap',
  },
  partQuantity: {
    fontSize: 12,
    fontWeight: 'bold',
    backgroundColor: '#ff6b6b',
    color: '#ffffff',
    padding: '8px 12px',
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  measurementsContainer: {
    marginVertical: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e3e8ed',
    width: '100%',
  },
  measurementsTitle: {
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#495057',
    fontSize: 16.5,
  },
  measurementRow: {
    flexDirection: 'column',
    gap: 2,
  },
  measurement: {
    backgroundColor: '#f8f9ff',
    padding: 4,
    borderRadius: 6,
    borderLeftWidth: 2,
    borderLeftColor: '#667eea',
    width: '100%',
    marginBottom: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'nowrap',
    minHeight: 'auto',
  },
  measurementLabel: {
    fontSize: 9.75,
    fontWeight: 'bold',
    color: '#495057',
    marginBottom: 1,
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },
  measurementValue: {
    fontSize: 11.7,
    color: '#667eea',
    fontWeight: 'bold',
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },
  optionsContainer: {
    marginTop: 10,
    backgroundColor: '#f8f9fa',
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e3e8ed',
  },
  optionsTitle: {
    fontWeight: 'bold',
    marginBottom: 6,
    color: '#495057',
    fontSize: 10,
  },
  option: {
    color: '#28a745',
    marginBottom: 3,
    fontSize: 10,
  },
  notes: {
    backgroundColor: '#fef3c7',
    border: '1px solid #fbbf24',
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
  },
  notesTitle: {
    fontWeight: 'bold',
    color: '#92400e',
    fontSize: 6,
    marginBottom: 5,
  },
  notesContent: {
    color: '#78350f',
    fontSize: 5.5,
  },
  footer: {
    marginTop: 30,
    paddingTop: 20,
    borderTopWidth: 2,
    borderTopColor: '#667eea',
    textAlign: 'center',
  },
  footerStats: {
    fontSize: 6,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 8,
  },
  footerDate: {
    fontSize: 5,
    color: '#6b7280',
  },
});